--!strict

export type Paths = {
	ManualTree: string,
	ManualTreeTarget: string,
	TreeLeaves: string,
	ManualRock: string,
	ManualRockTarget: string,
	NPCPurchasePad: string,
	NPCPurchasePadTarget: string,
	StorageUpgradeButton: string,
	StorageUpgradeButtonTarget: string,
	CoalProcessor: string,
	CoalProcessorTarget: string,
	SellTouchPad: string,
	SellBillboard: string,
	SellBillboardLabel: string,
	SellScreenLabel: string,
	WorkerHomes: string,
	WorkerApproachPoints: string,
	TreeApproach: string,
	RockApproach: string,
	StorageApproach: string,
	CoalProcessorApproach: string,
	StorageDisplayAnchor: string,
	StorageDropTarget: string,
	PlayerSpawn: string,
}

return {}
