[package]
name = "ptekspy/classicidle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Cmdr = "evaera/cmdr@1.12.0"

[server-dependencies]
